### ISSUE TITLE
Sharing small payloads with other nodes timely

### ISSUE THREAD

**Issue by joachimneu** [asonnino/hotstuff#50]
I am using this implementation as an "SMR module" in a prototype where the effective transaction rate is quite low. In this case, transactions "get stuck" in the mempool (more specifically, the Runner of the PayloadMaker) as follows: Since the number of transactions pending at a node is low, https://github.com/asonnino/hotstuff/blob/main/mempool/src/payload.rs#L49 never makes a payload; so the only time a payload is made (and the few pending transactions are shared with other nodes) is when the node becomes leader, which with many nodes might take a while and so the transactions experience quite some latency.

If instead even small payloads were shared with other nodes timely, then other leaders could propose these transactions, leading to better latency (albeit probably more overhead in communicating smaller payloads).

As a workaround, since in my use case throughput is really low, it is quick to hack https://github.com/asonnino/hotstuff/blob/main/mempool/src/payload.rs#L47 so that it makes and shares a new payload for every incoming transaction.

For a more universal solution, one might want a new mempool config parameter controlling a timeout to get a behavior like "keep adding transactions to the payload in the making; make and share the payload either once it is big or once the timeout for the oldest pending transaction has expired". Let me know your thoughts, I'd be happy to modify accordingly and submit a pull request.

Btw, great code base, thanks for sharing!

**Comment by asonnino** [comment]
Sorry for the late reply, for whatever reason I didn't see this issue.. 

I understand the issue, I will currently refactoring the code a bit to have a smoother interface between consensus and mempool (which will solve this problem on the way). In the meantime, you can either configure the batch size of the mempool to a lower number (https://github.com/asonnino/hotstuff/blob/15f79f2811d1461a71b587a3d2525835f83249a7/benchmark/fabfile.py#L117) or implement a timer that ships the batch even if not full (as you suggested).
