### ISSUE TITLE
questions about environment

### ISSUE THREAD

**Issue by chuqingG** [asonnino/hotstuff#59]
What are your versions of python and fabric? I run `fab local` in a new tmux session and it will crash, which means the session will be killed. Thanks.

**Comment by asonnino** [comment]
Oh I may know what happened to you. Is it possible you tried to run `fab local` from within a tmux session? If that is the case, tmux should crash complaining that you cannot spawn nested tmux sessions. The command `fab local` is designed to be run natively, it will create any necessary tmux session on its own.

**Comment by chuqingG** [comment]
thanks! I got it wrong: (
