### ISSUE TITLE
CLI can not parse the command when multiple nodes are provided

### ISSUE THREAD

**Issue by AlianBenabdallah** [asonnino/hotstuff#71]
Hi, clap cannot parse the command `client [...] --nodes IP1:PORT1 IP2:PORT2` when multiple IP:PORT are provided.
 https://github.com/asonnino/hotstuff/blob/40180b41793ede5e98c75c602a429358567090f7/node/src/client.rs#L36

 I think adding `multiple=true` to this line would solve the issue.

**Comment by asonnino** [comment]
Should be fixed through https://github.com/asonnino/hotstuff/commit/ce476e2fc0210cbb92405ce9c1af5831fa8c5b8e
