### ISSUE TITLE
A message transfer between two honest nodes can be canceled

### ISSUE THREAD

**Issue by AlianBenabdallah** [asonnino/hotstuff#74]
In two places of the code, we call `ReliableSender::broadcast()` and wait for 2f+1 answers. 
https://github.com/asonnino/hotstuff/blob/ce476e2fc0210cbb92405ce9c1af5831fa8c5b8e/mempool/src/quorum_waiter.rs#L70-L83
https://github.com/asonnino/hotstuff/blob/ce476e2fc0210cbb92405ce9c1af5831fa8c5b8e/consensus/src/proposer.rs#L94-L121

This function returns handlers that cancel the transfer when they are dropped. Since we wait for 2f+1 answers before dropping the handlers, it is possible that `f` honest nodes do not receive the message. 

I suggest adding this line : 
`tokio::spawn(async move { while let Some(_) = wait_for_quorum.next().await {} });` at the end of these two code blocks so the handlers do not get dropped.

I ran two local benchmark of the actual code base after adding this line and obtained 3x more `Committed ->` logs. (1500 vs 4600)

**Comment by asonnino** [comment]
But what if the `f` remaining nodes are Byzantine? Won't we eventually run out of memory?

**Comment by AlianBenabdallah** [comment]
Indeed. Maybe we can add a timeout after which the future is dropped or build a more robust solution like the one you suggested by mail. 
With the current code, if f malicious nodes send an Ack very quickly then the remaining f honest nodes will have to get the block through the synchronizer.
Moreover, if every node is honest then only 2f nodes will receive the message. The subset of nodes receiving the message is also not fixed.
For some reasons, when I look at the logs, I notice some very long periods without any commit. Ensuring that every honest node receives a broadcast from another honest node seemed to fix that.

**Comment by asonnino** [comment]
Good idea. A timeout is an easy fix that doesn't require big refactoring

**Comment by asonnino** [comment]
https://github.com/asonnino/hotstuff/pull/76
